name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker buildx build --platform windows/amd64 -t <lokeshjoshi053>/<hey_node>:latest -f hey_node.Dockerfile .
      env:
        DOCKER_USERNAME: ${{ secrets.lokeshjoshi053 }}
        DOCKER_PASSWORD: ${{ secrets.Lj9662@@@ }}