name: Build and Publish Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t lokeshjoshi053/hey_node:node .
      - name: Tag Docker image
        run: docker tag lokeshjoshi053/hey_node:node lokeshjoshi053/hey_node:node
      - name: Push Docker image
        run: docker push lokeshjoshi053/hey_node:node && docker push lokeshjoshi053/hey_node:node